### ISSUE TITLE
handling base_margin in xgboost in PDP

### ISSUE THREAD

**Issue by aravind211** [bgreenwell/pdp#67] opened 2018-03-09 11:47 UTC
Hi bgreenwell. Thanks for creating the package, its fantastic.

I had a quick question regarding the handling of base_margin within this package. The output seems to be affect by the values supplied to the base_margin in the design matrix (for gamma/poisson xgboost). Is there any fix for this?

**Comment by bgreenwell** [comment] 2018-03-09 21:33
I'm currently not sure the best way to handle offsets within `pdp`. I think the best approach is manually via the `pred.fun` argument, but I will put some more thought into it since this seems to be a recurring issue.

**Comment by aravind211** [comment] 2018-03-10 05:30
Can you please give an example of how i could introduce the offset through the pred.fun argument.

**Comment by bgreenwell** [comment] 2018-03-21 18:49
Ahh, sorry for nat seeing your latest comment. Do you have a small example involving `base_margin` you can provide (e.g., a small Poisson regression)? I do not have any examples off hand.

**Comment by bgreenwell** [comment] 2018-08-07 17:38
Offsets are a "per row" bias adjustment for the repsonse only used in training and therefore I do not think it applies to PDPs (which generate predictions over a grid of new points). Closing this issue.

**Closed by bgreenwell** 2018-08-07 17:38 UTC
